---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prom-script
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute..
      
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']
      - job_name: 'node1'
        static_configs:
        - targets: ['34.93.84.175:9200']
      - job_name: 'apache'
        static_configs:
        - targets: ['34.93.254.219:9118']

